name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    environment:
      name: production
      url: https://robotics-club.utm.utoronto.ca/
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: remove existing team repo
        run: rm -rf src/lib/team

      - uses: actions/checkout@v4
        with:
          repository: UTM-Robotics/team-images
          path: 'src/lib/team'
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: create env files
        run: echo "${{ secrets.ENV }}" > .env;

      - name: compose build
        run: docker compose build

      - name: compose up
        run: docker compose up -d

      - name: cleanup
        run: |
          docker system prune -a -f
